_

diff --git a/SmartList/bin/createlist b/SmartList/bin/createlist
--- a/SmartList/bin/createlist
+++ b/SmartList/bin/createlist
@@ -6,7 +6,7 @@ $O || exec /bin/sh "$0" "$@"		  # we're in a buggy zsh
 #									#
 #	Created by S.R. van den Berg, The Netherlands			#
 #########################################################################
-#$Id: createlist,v 1.25 1994/01/28 11:56:36 berg Exp $
+#$Id: createlist,v 1.26 1994/05/26 13:45:55 berg Exp $
 
 defaults=.etc
 
@@ -29,10 +29,11 @@ lockfile=lockfile	# /usr/local/bin/lockfile
 bin_procmail=SedBinDir/procmail
 
 DEVNULL=/dev/null
+etcpasswd=/etc/passwd
 EX_USAGE=64
 EX_UNAVAILABLE=69
 
-( lockfile ) 2>$DEVNULL
+( exec 2>$DEVNULL; lockfile )
 if $test $? != 64
 then
   $echo "Where is \"lockfile\"? It should be installed in your PATH" 1>&2
@@ -72,8 +73,8 @@ then
      exit $EX_UNAVAILABLE
   fi
   $rm -f $bin_procmail
-  $ln -s $procmail $bin_procmail 2>/dev/null ||
-  $ln $procmail $bin_procmail 2>/dev/null ||
+  $ln -s $procmail $bin_procmail 2>$DEVNULL ||
+  $ln $procmail $bin_procmail 2>$DEVNULL ||
    ( $cat >$bin_procmail <<HERE
 #! /bin/sh
 :
@@ -113,13 +114,19 @@ case "$list" in
      1>&2; exit $EX_USAGE;;
 esac
 
+if $grep -i -e "^$list:" $etcpasswd >$DEVNULL
+then
+  $echo "createlist: You can't pick a listname equal to an existing username" \
+   1>&2; exit $EX_USAGE
+fi
+
 umask `$sed -n -e 's/^[^#]*UMASK=[^0-9]*\([0-9]*\).*$/\1/p' $defaults/rc.init`
 
 $chmod go+x . .bin $defaults			# to preserve sanity
 
 if $mkdir "$list" 2>$DEVNULL
 then
-  $chmod g+s "$list" 2>/dev/null	# to ensure the gid is inherited
+  $chmod g+s "$list" 2>$DEVNULL		# to ensure the gid is inherited
 else $echo "createlist: \"$list\" already exists" 1>&2; exit $EX_USAGE
 fi
 cd "$list"
diff --git a/SmartList/bin/flush_digests b/SmartList/bin/flush_digests
--- a/SmartList/bin/flush_digests
+++ b/SmartList/bin/flush_digests
@@ -9,7 +9,7 @@ $O || exec /bin/sh "$0" "$@"		  # we're in a buggy zsh
 #									#
 #	Created by S.R. van den Berg, The Netherlands			#
 #########################################################################
-#$Id: flush_digests,v 1.11 1993/11/24 19:45:39 berg Exp $
+#$Id: flush_digests,v 1.12 1994/05/26 13:46:01 berg Exp $
 
 test=test		# /bin/test
 mkdir=mkdir		# /bin/mkdir
@@ -87,12 +87,15 @@ then
   fi
 
 else
-  a=`$dirname "$0"`/..
-  if cd "$a"
+  if test -z "$cronlist"	# for backward compatibility
   then
-  :
-  else
-     $echo "Can't chdir to $a" 1>&2 ; exit 66
+     a=`$dirname "$0"`/..
+     if cd "$a"
+     then
+     :
+     else
+	$echo "Can't chdir to $a" 1>&2 ; exit 66
+     fi
   fi
   for a in dummy */.digest.params
   do
