_

diff --git a/SmartList/bin/flush_digests b/SmartList/bin/flush_digests
--- a/SmartList/bin/flush_digests
+++ b/SmartList/bin/flush_digests
@@ -8,35 +8,39 @@
 #									#
 #	Created by S.R. van den Berg, The Netherlands			#
 #########################################################################
-#$Id: flush_digests,v 1.1 1993/03/04 15:31:02 berg Exp $
+#$Id: flush_digests,v 1.2 1993/03/05 14:39:54 berg Exp $
 
 test=test		# /bin/test
 mkdir=mkdir		# /bin/mkdir
 sed=sed			# /bin/sed
 cat=cat			# /bin/cat
 rm=rm			# /bin/rm
+ls=ls			# /bin/ls
 echo=echo		# /bin/echo
+touch=touch		# /bin/touch
 dirname=dirname		# /bin/dirname
 lockfile=lockfile	# /usr/local/bin/lockfile
 
-$test $# != 1 -o $# = 1 -a .-c != ".$1" &&
+$test \( $# != 0 -a $# != 1 \) -o $# = 1 -a .-c != ".$1" &&
  $echo "Usage: flush_digests [-c]" 1>&2 && exit 64
 
 tmprequest=tmp.request
 tmpfrom=tmp.from
 
-if $test .-c = "$1"
+digestbody=archive/latest/digest.body
+
+if $test .-c = ".$1"
 then
   digestheader=archive/latest/digest.header
   digestadmin=digest.admin
   digestadmin2=archive/latest/$digestadmin
-  digestbody=archive/latest/digest.body
   digesttrailer=archive/latest/digest.trailer
 
   set `cat .digest.params`
   digest_age=$1; shift
   digest_size=$1; shift
   archive_hist=$1; shift
+  umask $1; shift
   SENDMAIL="$*"
 
   if senddigest $digest_age $digest_size $digestbody $digesttrailer \
@@ -69,7 +73,12 @@ HERE
 
 else
   a=`$dirname "$0"`/..
-  cd "$a" || $echo "Can't chdir to $a" 1>&2 && exit 67
+  if cd "$a"
+  then
+  :
+  else
+     $echo "Can't chdir to $a" 1>&2 ; exit 66
+  fi
   for a in */.digest.params dummy
   do
      if $test dummy != "$a"
@@ -80,6 +89,7 @@ else
 	$lockfile -l3600 tmp.lock
 	trap "$rm -f tmp.lock; exit 1" 1 2 3 15
 	$cat /dev/null >$tmprequest 2>$tmpfrom
+	$test -f $digestbody && $touch $digestbody
 	PATH=.:../.bin:$PATH ../.bin/flush_digests -c
 	trap "" 1 2 3 15
 	$rm -f tmp.lock
diff --git a/examples/mailstat b/examples/mailstat
--- a/examples/mailstat
+++ b/examples/mailstat
@@ -16,14 +16,15 @@
 #	Created by S.R. van den Berg, The Netherlands		#
 #	This file can be freely copied for any use.		#
 #################################################################
-#$Id: mailstat,v 1.12 1993/03/04 15:30:46 berg Exp $
+#$Id: mailstat,v 1.13 1993/03/05 14:39:48 berg Exp $
 
 #	This shell script expects the following programs to be in the
 #	PATH (paths given here are the standard locations, your mileage
 #	may vary (if the programs can not be found, extend the PATH or
 #	put their absolute pathnames in here):
 
-test=test		# /bin/test	(or built-in in /bin/sh)
+test=test		# /bin/test
+echo=echo		# /bin/echo
 expr=expr		# /bin/expr
 tty=tty			# /bin/tty
 sed=sed			# /bin/sed
@@ -68,15 +69,15 @@ do
 	 o*) MSoldlog=1; MSkeeplogfile=1;;
 	 t*) MSterse=1;;
 	 s*) MSsilent=1;;
-	 h*|\?*) echo 'Usage: mailstat [-klmots] [logfile]' 1>&2
-	    echo '	-k	keep logfile intact' 1>&2
-	    echo '	-l	long display format' 1>&2
-	    echo '	-m	merge any errors into one line' 1>&2
-	    echo '	-o	use the old logfile' 1>&2
-	    echo '	-t	terse display format' 1>&2
-	    echo '	-s	silent in case of no mail' 1>&2
+	 h*|\?*) $echo 'Usage: mailstat [-klmots] [logfile]' 1>&2
+	    $echo '	-k	keep logfile intact' 1>&2
+	    $echo '	-l	long display format' 1>&2
+	    $echo '	-m	merge any errors into one line' 1>&2
+	    $echo '	-o	use the old logfile' 1>&2
+	    $echo '	-t	terse display format' 1>&2
+	    $echo '	-s	silent in case of no mail' 1>&2
 	    exit $EX_USAGE;;
-	 *) echo 'Usage: mailstat [-klmots] [logfile]' 1>&2; exit $EX_USAGE;;
+	 *) $echo 'Usage: mailstat [-klmots] [logfile]' 1>&2; exit $EX_USAGE;;
      esac
   done
 done
@@ -103,11 +104,11 @@ then
      then
 	if $test -f "$LOGFILE"
 	then
-	   echo No mail arrived since \
+	   $echo No mail arrived since \
 	    `$expr match "\`LANG= LC_TIME= $ls -l \"$OLDLOGFILE\"
 	    \`" '.*[0-9] \\([A-Z][a-z][a-z] .[^ ] .....\\) [^ ]'`
 	else
-	   echo "Can't find your LOGFILE=$LOGFILE"
+	   $echo "Can't find your LOGFILE=$LOGFILE"
 	fi
      fi
      exit 1
@@ -115,7 +116,7 @@ then
 else
   if $test ."$LOGFILE" != .- && $tty -s
   then
-     echo \
+     $echo \
       "Most people don't type their own logfiles;  but, what do I care?" 1>&2
      MSterse=1
   fi
@@ -131,13 +132,13 @@ if $test .$MSterse = .
 then
   if $test .$MSlong = .1
   then
-     echo ""
-     echo "  Total Average  Number Folder"
-     echo "  ----- -------  ------ ------"
+     $echo ""
+     $echo "  Total Average  Number Folder"
+     $echo "  ----- -------  ------ ------"
   else
-     echo ""
-     echo "  Total  Number Folder"
-     echo "  -----  ------ ------"
+     $echo ""
+     $echo "  Total  Number Folder"
+     $echo "  -----  ------ ------"
   fi
 fi
 
