Handle BSD realloc()

diff --git a/src/autoconf b/src/autoconf
--- a/src/autoconf
+++ b/src/autoconf
@@ -1,7 +1,7 @@
 #! /bin/sh
 :
 # Copyright (c) 1990-1997, S.R. van den Berg, The Netherlands
-#$Id: autoconf,v 1.112 1998/11/06 05:35:29 guenther Exp $
+#$Id: autoconf,v 1.113 1998/11/06 06:21:00 guenther Exp $
 
 # All possible entries in autoconf.h:
 
@@ -83,6 +83,7 @@
 #	#define DEFflagsendmail ""
 #Ok	#define CF_no_procmail_yet
 #Ok	#define defPATH "PATH=$HOME/bin:/bin:/usr/bin:/usr/local/bin"
+#Ok	#define INEFFICIENTrealloc
 
 # A conforming ANSI compiler and POSIX library should not have any defines not
 # marked as "Ok" in the autoconf.h file.
@@ -423,7 +424,7 @@ unsigned sfork()
 }
 
 main(argc,argv)char*argv[];
-{ int goodlock,testlock,i,pip[2],pipw[2];unsigned otimet,dtimet;
+{ int goodlock,testlock,i,pip[2],pipw[2];time_t otimet,dtimet;
   static char filename[]="_locktst.l0";
   close(0);goodlock=0;testlock=FIRST_lock;signal(SIGPIPE,SIG_DFL);
   if(argc==2)
@@ -814,6 +815,57 @@ do
 done
 
 $RM _autotst.$O
+
+cat >_autotst.c <<HERE
+#include "$ACONF"
+#include "../config.h"
+#include <stdio.h>
+#ifndef STDLIB_H_MISSING
+#include <stdlib.h>
+#else
+void*malloc(),*realloc();
+#endif
+int main()
+{ char*p=0,*q=0;
+  size_t len=0,step=BLKSIZ,max=step*64,last=0;/* 1M on non-SMALLHEAP systems */
+  int count=-1;			     /* take into account the initial malloc */
+  while((len+step)<=max)
+   { /* touch at least every new page */
+     for(;last<len;last+=1024)
+	p[last]=last%127;
+     len+=step;
+     p=realloc(p,len);
+     if(!p)
+	break;
+     if(p!=q)
+	count++,q=p;
+   }
+  free(q);
+  printf("/* %d move%s in %d steps of size %d when reallocing */\n",
+	 count,count==1?"":"s",(int)(max/step),step);
+  if(step*(4*count+1)>max)
+   { puts("#define INEFFICIENTrealloc");
+     exit(1);
+   }
+  exit(0);
+}
+HERE
+
+echo 'Checking realloc implementation'
+
+if $MAKE _autotst >$DEVNULL 2>&1
+ test -f _autotst
+then
+ _autotst >_autotst.rrr
+ case "$?" in
+ 0) cat _autotst.rrr >>$ACONF;;
+ 1) cat _autotst.rrr >>$ACONF
+    echo 'Sorry, repeatedly reallocing is inefficient';;
+ *) echo "The test program failed somehow.  Assuming realloc is fine";;
+ esac
+fi
+
+$RM _autotst.$O _autotst _autotst.rrr
 
 cat >_autotst.c <<HERE
 #include "includes.h"
